spring:
  application:
    name: eureka-server
  profiles:
    active: test  # 指定使用那个配置

---
server:
  port: 8761
eureka:
  client:
    fetch-registry: false # 是否获取注册信息, 目前只有自己一个eureka-server，无需同步注册信息
    register-with-eureka: false # 是否注册到eureka， 因为自己就是eureka-server所以无需注册
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 暴露服务地址
  instance:
    hostname: localhost
spring:
  profiles: test

#看到所有支持的状态查询，需要配置
#访问路径 http://localhost:8761/actuator  http://localhost:8761/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字
  endpoint:
    health:
      show-details: always  #显示所有健康状态

#配置多个服务中心，集群
#peer1,peer2均为hostname,因为服务都跑在自己的电脑上，所以要在hosts文件里做了如下的映射：127.0.0.1 peer1 peer2
---
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
  instance:
    hostname: peer1
spring:
  profiles: peer1
---
server:
  port: 8762
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:8761/eureka/
  instance:
    hostname: peer2
spring:
  profiles: peer2
