server:
  port: 9001

spring:
  application:
    name: stream-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务注册于发现地址
#        namespace: DEV_GROUP  #命名空间
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092    #Kafka的消息中间件服务器
          zk-nodes: 127.0.0.1:2128   #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true   #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          auto-add-partitions: true  #自动增加分区
      bindings:
        #这里用stream给我们提供的默认output，后面会讲到自定义output
        output:
          #消息发往的目的地  topic名称
          destination: stream-demo
          #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
        #自定义 output  消息通道名称
        myOutput:
          #消息发往的目的地 topic名称
          destination: stream-demo
          #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
          producer:
            #分区的主键，根据什么来分区，下面的payload.id只是一个对象的id用于做为Key，用来说明的。希望不要误解
            partitionKeyExpression: payload.id
            #Key和分区数量进行取模去分配消息，这里分区数量配置为2
            partitionCount: 2