server:
  port: 8001

spring:
  application:
    name: sentinel_demo
  cloud:
    sentinel:    # sentinel dashboard 配置
      transport:
        dashboard: localhost:8080    #sentinel服务地址
#      enabled: true

