spring:
  application:
    name: comsume-server # 在eureka中此值作为vipaddress,在发现服务时使用
  boot:
    admin:
      client:
        url: http://localhost:8769

server:
  port: 8767
logging:
  level:
    root: info
# eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    #获取服务地址
#      defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/ #服务中心，获取多个

feign:
  hystrix:
    enabled: true