server:
  port: 8769

spring:
  application:
    name: admin-server

#配置eureka服务端地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/