spring:
  application:
    name: product-server # 在eureka中此值作为vipaddress,在发现服务时使用
  boot:
    admin:
      client:
        url: http://localhost:8769 #获取监控器admin的服务地址
  datasource:                      # mySql
    url: jdbc:mysql://10.2.12.35:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: fxjyadmin
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  #数据库连接池druid
  redis:
#    host: 10.2.12.117  # Redis服务器地址
#    port: 6380         # Redis服务器连接端口
    host: 127.0.0.1    # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    timeout: 3000      # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
  cache:
    cache-names: c1    # 缓存的名字

server:
  port: 8768
#spring:
#  datasource:
#    platform: h2
#    schema: classpath:schema.sql
#    data: classpath:data.sql
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
logging:
  level:
    root: info
    org.hibernate: info


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/

#看到所有支持的状态查询，需要配置
#访问路径 http://localhost:8761/actuator  http://localhost:8761/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字
  endpoint:
    health:
      show-details: always  #显示所有健康状态
# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.chuan.demo.entity
#  type-handlers-package:

#zuul路由配置
#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
#zuul.routes.baidu.path=/it/**
#zuul.routes.baidu.url=http://www.ityouknow.com/
zuul:
  routes:                             # zuul.routes 是固定的
    baidu:                            # baidu 是可以随便写的，但最好根据要路由的服务取
      path: "/it/**"
      url: http://www.ityouknow.com/

# 自定义启动器
test:
  service:
    enable: true
    config: a,b,c,d,1,2,3